---
version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: metrics
    restart: unless-stopped
    volumes:
      - ./configs/metrics.yml:/etc/metrics/metrics.yml
      - prometheus_data:/metrics
    command:
      - '--config.file=/etc/metrics/metrics.yml'
      - '--storage.tsdb.path=/metrics'
      - '--web.console.libraries=/etc/metrics/console_libraries'
      - '--web.console.templates=/etc/metrics/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    restart: unless-stopped
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana