---
version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}
  postgres_data: {}

services:
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_DB: "tasks"
      POSTGRES_USER: "postgres"
  prometheus:
    image: prom/prometheus:latest
    container_name: metrics
    restart: unless-stopped
    volumes:
      - ./configs/metrics.yml:/etc/metrics/metrics.yml
      - prometheus_data:/metrics
    command:
      - '--config.file=/etc/metrics/metrics.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    restart: unless-stopped
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana