global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'consumer'
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: 'producer'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]