// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: pkg/proto/grpc_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TaskProducerClient is the client API for TaskProducer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskProducerClient interface {
	GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	FinishTask(ctx context.Context, in *TaskFinishedRequest, opts ...grpc.CallOption) (*TaskFinishedResponse, error)
}

type taskProducerClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskProducerClient(cc grpc.ClientConnInterface) TaskProducerClient {
	return &taskProducerClient{cc}
}

func (c *taskProducerClient) GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, "/proto.TaskProducer/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskProducerClient) FinishTask(ctx context.Context, in *TaskFinishedRequest, opts ...grpc.CallOption) (*TaskFinishedResponse, error) {
	out := new(TaskFinishedResponse)
	err := c.cc.Invoke(ctx, "/proto.TaskProducer/FinishTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskProducerServer is the server API for TaskProducer service.
// All implementations must embed UnimplementedTaskProducerServer
// for forward compatibility
type TaskProducerServer interface {
	GetTask(context.Context, *TaskRequest) (*TaskResponse, error)
	FinishTask(context.Context, *TaskFinishedRequest) (*TaskFinishedResponse, error)
	mustEmbedUnimplementedTaskProducerServer()
}

// UnimplementedTaskProducerServer must be embedded to have forward compatible implementations.
type UnimplementedTaskProducerServer struct {
}

func (UnimplementedTaskProducerServer) GetTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskProducerServer) FinishTask(context.Context, *TaskFinishedRequest) (*TaskFinishedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishTask not implemented")
}
func (UnimplementedTaskProducerServer) mustEmbedUnimplementedTaskProducerServer() {}

// UnsafeTaskProducerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskProducerServer will
// result in compilation errors.
type UnsafeTaskProducerServer interface {
	mustEmbedUnimplementedTaskProducerServer()
}

func RegisterTaskProducerServer(s grpc.ServiceRegistrar, srv TaskProducerServer) {
	s.RegisterService(&TaskProducer_ServiceDesc, srv)
}

func _TaskProducer_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskProducerServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TaskProducer/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskProducerServer).GetTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskProducer_FinishTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskFinishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskProducerServer).FinishTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TaskProducer/FinishTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskProducerServer).FinishTask(ctx, req.(*TaskFinishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskProducer_ServiceDesc is the grpc.ServiceDesc for TaskProducer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskProducer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TaskProducer",
	HandlerType: (*TaskProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTask",
			Handler:    _TaskProducer_GetTask_Handler,
		},
		{
			MethodName: "FinishTask",
			Handler:    _TaskProducer_FinishTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/grpc_service.proto",
}
